apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    volume-type: vault
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-server.example.com
    path: /opt/nfsshare/vault

