apiVersion: v1
kind: Service
metadata:
  labels:
    name: vault-ui
  name: vault-ui
spec:
  selector:
    app: vault-ui
  type: ClusterIP
  ports:
  - name: vault-ui
    protocol: TCP
    port: 8000
